apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 000-account-setup
  labels:
    platform: ibm
    code: '000'
  annotations:
    displayName: Account setup
    description: Sets up an IBM Cloud account with required Financial Services reference architecture settings
spec:
  modules:
    - name: ibm-resource-group
      alias: at_resource_group
      default: true
      variables:
        - name: name
          important: true
        - name: provision
          value: false
          important: true
    - name: ibm-activity-tracker
      alias: at-us-east
      variables:
        - name: resource_location
          value: "us-east"
          scope: module
        - name: provision
          value: true
    - name: ibm-activity-tracker
      alias: at-us-south
      variables:
        - name: resource_location
          value: "us-south"
          scope: module
        - name: provision
          value: true
    - name: ibm-activity-tracker
      alias: at-eu-de
      variables:
        - name: resource_location
          value: "eu-de"
          scope: module
        - name: provision
          value: true
    - name: ibm-activity-tracker
      alias: at-eu-gb
      variables:
        - name: resource_location
          value: "eu-gb"
          scope: module
        - name: provision
          value: true
    - name: ibm-onboard-fs-account
      variables:
        - name: action
          value: enable
        - name: mfa
          value: TOTP4ALL
        - name: restrict_create_service_id
          value: RESTRICTED
        - name: restrict_create_platform_apikey
          value: RESTRICTED
  variables:
    - name: name_prefix
      alias: common_name_prefix
    - name: region
