apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 000-account-setup
spec:
  modules:
    - name: ibm-resource-group
      variables:
        - name: resource_group_name
          alias: hpcs_resource_group_name
          scope: global
        - name: provision
          alias: hpcs_resource_group_provision
          scope: global
          value: false
    - name: ibm-activity-tracker
      alias: at-us-east
      variables:
        - name: resource_location
          value: "us-east"
          scope: module
        - name: provision
          value: true
    - name: ibm-activity-tracker
      alias: at-us-south
      variables:
        - name: resource_location
          value: "us-south"
          scope: module
        - name: provision
          value: true
    - name: ibm-activity-tracker
      alias: at-eu-de
      variables:
        - name: resource_location
          value: "eu-de"
          scope: module
        - name: provision
          value: true
    - name: ibm-activity-tracker
      alias: at-eu-gb
      variables:
        - name: resource_location
          value: "eu-gb"
          scope: module
        - name: provision
          value: true
    - name: ibm-onboard-fs-account
      variables:
        - name: action
          value: enable
        - name: mfa
          value: TOTP4ALL
        - name: restrict_create_service_id
          value: RESTRICTED
        - name: restrict_create_platform_apikey
          value: RESTRICTED
    - name: hpcs
      variables:
        - name: provision
          value: false
        - name: region
          alias: hpcs_region
        - name: name_prefix
          alias: hpcs_name_prefix
          scope: global
        - name: name
          required: true
    - name: ibm-iam-service-authorization
      alias: vsi-encrypt-auth
      variables:
        - name: source_service_name
          value: server-protect
        - name: target_service_name
          value: hs-crypto
        - name: roles
          value:
            - Reader
      dependencies:
        - name: target_resource_group
          ref: resource_group
    - name: ibm-iam-service-authorization
      alias: cos-encrypt-auth
      variables:
        - name: source_service_name
          value: cloud-object-storage
        - name: target_service_name
          value: hs-crypto
        - name: roles
          value:
            - Reader
      dependencies:
        - name: target_resource_group
          ref: resource_group
  variables:
    - name: cs_resource_group_provision
    - name: name_prefix
      alias: cs_name_prefix
    - name: region
    - name: cs_resource_group_name
