apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 100-shared-services
  labels:
    platform: ibm
    code: 100
  annotations:
    displayName: Shared services
    description: Managed services that are shared across the management and workload networks
spec:
  modules:
    - name: ibm-resource-group
      variables:
        - name: resource_group_name
          alias: cs_resource_group_name
          scope: global
        - name: provision
          alias: cs_resource_group_provision
          scope: global
    - name: ibm-resource-group
      alias: kms_resource_group
      variables:
        - name: resource_group_name
          alias: kms_resource_group_name
          scope: global
        - name: provision
          alias: kms_resource_group_provision
          scope: global
          value: true
      dependencies:
        - name: sync
          ref: resource_group
    - name: ibm-kms
      alias: kms
      variables:
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
        - name: name
          required: true
      dependencies:
        - name: resource_group
          ref: kms_resource_group
    - name: ibm-access-group
    - name: ibm-object-storage
    - name: sysdig
    - name: logdna
    - name: ibm-iam-service-authorization
      alias: vsi-encrypt-auth
      variables:
        - name: source_service_name
          value: server-protect
        - name: roles
          value:
            - Reader
      dependencies:
        - name: target_resource_group
          ref: kms_resource_group
        - name: target_resource
          ref: kms
    - name: ibm-iam-service-authorization
      alias: cos-encrypt-auth
      variables:
        - name: roles
          value:
            - Reader
      dependencies:
        - name: target_resource_group
          ref: kms_resource_group
        - name: target_resource
          ref: kms
        - name: source_resource
          ref: cos
    - name: ibm-iam-service-authorization
      alias: flow-log-auth
      variables:
        - name: source_service_name
          value: is
        - name: source_resource_type
          value: flow-log-collector
        - name: roles
          value:
            - Writer
      dependencies:
        - name: target_resource_group
          ref: resource_group
        - name: target_resource
          ref: cos
    - name: ibm-iam-service-authorization
      alias: vsi-encrypt-auth
      variables:
        - name: source_service_name
          value: server-protect
        - name: roles
          value:
            - Reader
      dependencies:
        - name: source_resource_group
          ref: resource_group
        - name: target_resource_group
          ref: kms_resource_group
        - name: target_resource
          ref: kms
    - name: ibm-iam-service-authorization
      alias: kube-encrypt-auth
      variables:
        - name: source_service_name
          value: containers-kubernetes
        - name: roles
          value:
            - Reader
      dependencies:
        - name: source_resource_group
          ref: resource_group
        - name: target_resource_group
          ref: kms_resource_group
        - name: target_resource
          ref: kms
    - name: ibm-cert-manager
      variables:
        - name: private_endpoint
          value: false
      dependencies:
        - name: resource_group
    - name: ibm-iam-service-authorization
      alias: vpn-cert-manager-auth
      variables:
        - name: source_service_name
          value: is
        - name: source_resource_type
          value: vpn-server
        - name: roles
          value:
            - Writer
        - name: target_service_name
          value: cloudcerts
  variables:
    - name: kms_resource_group_provision
    - name: cs_resource_group_provision
    - name: name_prefix
      alias: cs_name_prefix
    - name: region
    - name: cs_resource_group_name
    - name: kms_service
