apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 110-mzr-management
  labels:
    platform: ibm
    code: 110
  annotations:
    displayName: MZR Management VPC
    description: Multi-Zone Management VPC with VPN and Bastion servers
spec:
  modules:
    - name: ibm-resource-group
      alias: kms_resource_group
      variables:
        - name: provision
          value: false
    - name: ibm-resource-group
      alias: at_resource_group
      variables:
        - name: provision
          value: false
    - name: ibm-kms
      alias: kms
      variables:
        - name: provision
          value: false
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
          value: ""
      dependencies:
        - name: resource_group
          ref: kms_resource_group
    - name: ibm-resource-group
      variables:
        - name: resource_group_name
          alias: mgmt_resource_group_name
          scope: global
        - name: provision
          alias: mgmt_resource_group_provision
          scope: global
    - name: ibm-access-group
    - name: ibm-vpc
      variables:
        - name: address_prefix_count
          value: 4
        - name: address_prefixes
          value:
            - 10.10.0.0/18
            - 10.20.0.0/18
            - 10.30.0.0/18
            - 10.1.0.0/18
    - name: ibm-flow-logs
      dependencies:
        - name: target
          ref: ibm-vpc
        - name: cos_bucket
          ref: flow_log_bucket
    - name: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      alias: worker-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: worker
        - name: ipv4_cidr_blocks
          value:
            - 10.10.10.0/24
            - 10.20.10.0/24
            - 10.30.10.0/24
      dependencies:
        - name: gateways
          ref: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      alias: vpe-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: vpe
        - name: ipv4_cidr_blocks
          value:
            - 10.10.20.0/24
            - 10.20.20.0/24
            - 10.30.20.0/24
    - name: ibm-vpc-subnets
      alias: vpn-subnets
      variables:
        - name: _count
          value: 1
        - name: label
          value: vpn
        - name: ipv4_cidr_blocks
          value:
            - 10.10.30.0/24
    - name: ibm-vpc-subnets
      alias: bastion-subnets
      variables:
        - name: _count
          value: 2
        - name: label
          value: bastion
        - name: zone_offset
          value: 1
        - name: ipv4_cidr_blocks
          value:
            - 10.20.30.0/24
            - 10.30.30.0/24
    - name: ibm-vpc-ssh
      alias: mgmt_ssh_vpn
      variables:
        - name: label
          value: vpn
    - name: ibm-vpc-vpn-gateway
      dependencies:
        - name: subnets
          ref: vpn-subnets
    - name: vsi-vpn
      variables:
        - name: kms_enabled
          value: true
      dependencies:
        - name: subnets
          ref: vpn-subnets
        - name: vpcssh
          ref: mgmt_ssh_vpn
    - name: ibm-vpc-ssh
      alias: mgmt_ssh_bastion
      variables:
        - name: label
          value: bastion
    - name: vsi-bastion
      variables:
        - name: image_name
          scope: module
        - name: kms_enabled
          value: true
      dependencies:
        - name: subnets
          ref: bastion-subnets
        - name: vpcssh
          ref: mgmt_ssh_bastion
    - name: ibm-resource-group
      alias: cs_resource_group
      variables:
        - name: provision
          value: false
    - name: ibm-object-storage
      alias: cos
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-kms-key
      variables:
        - name: provision
          value: true
      dependencies:
        - name: kms
          ref: kms
    - name: ibm-activity-tracker
      variables:
        - name: provision
          value: false
      dependencies:
        - name: resource_group
          ref: at_resource_group
    - name: sysdig
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: ibm-object-storage-bucket
      alias: flow_log_bucket
      variables:
        - name: label
          value: flow-logs
        - name: allowed_ip
          value:
            - 0.0.0.0/0
    - name: ibm-vpe-gateway
      alias: vpe-cos
      dependencies:
        - name: resource
          ref: cos
        - name: subnets
          ref: vpe-subnets
  variables:
    - name: mgmt_resource_group_name
    - name: mgmt_resource_group_provision
    - name: region
    - name: ibmcloud_api_key
    - name: name_prefix
      alias: mgmt_name_prefix
      required: true
    - name: cs_resource_group_name
    - name: cs_name_prefix
    - name: mgmt_ssh_vpn_public_key
      value: ""
    - name: mgmt_ssh_vpn_private_key
      value: ""
    - name: mgmt_ssh_bastion_public_key
      value: ""
    - name: mgmt_ssh_bastion_private_key
      value: ""
    - name: mgmt_ssh_vpn_public_key_file
    - name: mgmt_ssh_vpn_private_key_file
    - name: mgmt_ssh_bastion_public_key_file
    - name: mgmt_ssh_bastion_private_key_file
    - name: kms_service
