apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 160-openshift-dev-tools
spec:
  modules:
    - name: ibm-resource-group
      variables:
        - name: provision
          value: false
        - name: resource_group_name
          alias: mgmt_resource_group_name
          scope: global
    - name: ibm-ocp-vpc
      dependencies:
        - name: subnets
          optional: true
        - name: cos
          optional: true
        - name: vpc
          optional: true
      variables:
        - name: exists
          value: true
        - name: name
          required: true
        - name: vpc_subnet_count
          value: 0
        - name: vpc_subnets
          value: "[]"
        - name: cos_id
          value: ""
        - name: vpc_name
          value: ""
        - name: login
          value: true
    - name: ibm-resource-group
      alias: cs_resource_group
      variables:
        - name: provision
          value: false
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: namespace
      variables:
        - name: name
          value: tools
    - name: ibm-image-registry
      variables:
        - name: registry_namespace
          required: true
          scope: global
    - name: cluster-config
      variables:
        - name: banner_text
          value: Management
    - name: argocd
    - name: dashboard
    - name: pactbroker
    - name: artifactory
    - name: sonarqube
    - name: tekton
    - name: tekton-resources
    - name: source-control
  variables:
    - name: resource_group_name
    - name: region
    - name: ibmcloud_api_key
      required: true
    - name: registry_namespace
      required: true
    - name: name_prefix
      alias: mgmt_name_prefix
      required: true