apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 170-openshift-argocd
  labels:
    code: '170'
  annotations:
    displayName: OpenShift ArgoCD
    description: Provision ArgoCD on OpenShift
spec:
  modules:
    - name: ocp-login
      variables:
        - name: server_url
          required: true
        - name: login_user
          value: apikey
        - name: login_password
          alias: ibmcloud_api_key
          scope: global
    - name: namespace
      variables:
        - name: name
          value: tools
    - name: cluster-config
      alias: config
      variables:
        - name: banner_text
          value: Workload
        - name: banner_background_color
          value: red
    - name: argocd
  variables:
    - name: config_banner_text
