apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 300-cp-integration
spec:
  modules:
    - name: ocp-login
    - name: argocd-bootstrap
    - name: gitops-cp-mq
    - name: gitops-cp-ace
    - name: gitops-cp-apic
