import {Inject} from 'typescript-ioc';

import {ModuleDocumentationApi} from './module-documentation.api';
import {TerraformBuilderApi} from '../terraform-builder';
import {SelectedModuleResolverImpl} from '../module-selector/selected-modules.resolver';
import {
  Catalog,
  CatalogV2Model,
  Module,
  ModuleDependency,
  ModuleDoc,
  ModuleOutput,
  ModuleOutputRef,
  ModuleProvider,
  ModuleRef,
  ModuleVariable,
  ModuleVersion,
  SingleModuleVersion,
  Stage,
  TerraformComponent
} from '../../models';
import {getIascableVersion} from '../../util/iascable-version';
import {isUndefined} from '../../util/object-util';
import {ModuleVersionNotFound} from '../../util/version-resolver';

export class ModuleDocumentation implements ModuleDocumentationApi {
  @Inject
  terraformBuilder!: TerraformBuilderApi;

  async generateDocumentation(module: Module, catalogModel: CatalogV2Model, moduleList?: SingleModuleVersion[]): Promise<ModuleDoc> {

    const catalog: Catalog = Catalog.fromModel(catalogModel)

    const currentVersion: ModuleVersion = this.latestModuleVersion(module)

    const contents = `
# ${module.displayName || module.name} module

${module.description}

${module.documentation || ''}

## Software dependencies

The module depends on the following software components:

### Terraform version

${this.terraformVersion(currentVersion)}

### Terraform providers

${this.terraformProviders(currentVersion)}

### Module dependencies

${this.moduleDependencies(currentVersion)}

## Example usage

[Refer to examples for more details](${this.examplePath(module)})

\`\`\`
${await this.example(module, catalog, moduleList)}\`\`\`

## Module details

### Inputs

${this.moduleVariables(currentVersion)}

### Outputs

${this.moduleOutputs(currentVersion)}

## Resources

- [Documentation](https://operate.cloudnativetoolkit.dev)
- [Module catalog](https://modules.cloudnativetoolkit.dev)

> License: ${this.license(module)} | Generated by iascable (${getIascableVersion()})
`

    return new ModuleDoc({contents, moduleName: module.name})
  }

  latestModuleVersion(module: Module): ModuleVersion {
    if (!module.versions || module.versions.length === 0) {
      throw new ModuleVersionNotFound(module, 'latest')
    }

    return module.versions[0]
  }

  terraformVersion(moduleVersion: ModuleVersion): string {
    const versionString = (moduleVersion.terraformVersion || '>= v0.15').replace('>', '\\>')

    return `- ${versionString}`
  }

  terraformProviders(moduleVersion: ModuleVersion): string {
    if (!moduleVersion.providers || moduleVersion.providers.length === 0) {
      return 'None'
    }

    const moduleProvider = (provider: ModuleProvider): string => {
      return `- ${provider.name} (${provider.source})`
    }

    return moduleVersion.providers.map(moduleProvider).join('\n')
  }

  moduleDependencies(moduleVersion: ModuleVersion): string {
    if (!moduleVersion.dependencies || moduleVersion.dependencies.length === 0) {
      return 'None'
    }

    const moduleDependency = (dep: ModuleDependency): string => {
      const refString = (ref: ModuleRef) => `[${ref.source}](https://${ref.source}) (${ref.version})`

      if (dep.interface) {
        return `- ${dep.id} - interface ${dep.interface}`
      } else if (dep.refs && dep.refs?.length === 1) {
        return `- ${dep.id} - ${refString(dep.refs[0])}`
      } else if (dep.refs && dep.refs?.length > 0) {
        const modules: string = dep.refs.map(ref => `    - ${refString(ref)}`).join('\n')

        return `- ${dep.id} - one of:
${modules}
`
      } else {
        return `- ${dep.id}`
      }
    }

    return moduleVersion.dependencies.map(moduleDependency).join('\n')
  }

  examplePath(module: Module): string {
    if (!module.examplePath) {
      return `test/stages`
    }

    return module.examplePath
  }

  async example(module: Module, catalog: Catalog, moduleList?: SingleModuleVersion[]): Promise<string> {
    const modules: SingleModuleVersion[] = moduleList ? moduleList : new SelectedModuleResolverImpl(catalog).resolve([module])

    const terraform: TerraformComponent = await this.terraformBuilder.buildTerraformComponent(modules, catalog)

    const currentStage: Stage[] = Object.values(terraform.stages).filter(stage => stage.source === module.id)

    if (!currentStage || currentStage.length === 0) {
      return ''
    }

    currentStage[0].module.version.version = ''

    return currentStage[0].asString(terraform.stages)
  }

  moduleVariables(moduleVersion: ModuleVersion): string {
    if (!moduleVersion.variables || moduleVersion.variables.length === 0) {
      return 'None'
    }

    const variableHeader = (): string => {
      return `| Name | Description | Required | Default | Source |
|------|-------------|---------|----------|--------|`
    }

    const moduleSource = (ref?: ModuleOutputRef): string => {
      if (!ref) {
        return ''
      }

      return `${ref.id}.${ref.output}`
    }

    const moduleVariable = (variable: ModuleVariable): string => {
      return `| ${variable.name} | ${variable.description} | ${isUndefined(variable.default || variable.defaultValue) ? 'true' : ''} | ${variable.default || variable.defaultValue || ''} | ${moduleSource(variable.moduleRef)} |`
    }

    return `${variableHeader()}
${moduleVersion.variables.map(moduleVariable).join('\n')}
`
  }

  moduleOutputs(moduleVersion: ModuleVersion): string {
    if (!moduleVersion.outputs || moduleVersion.outputs.length === 0) {
      return 'None'
    }

    const outputHeader = (): string => {
      return `| Name | Description |
|------|-------------|`
    }

    const moduleOutput = (output: ModuleOutput): string => {
      return `| ${output.name} | ${output.description} |`
    }

    return `${outputHeader()}
${moduleVersion.outputs.map(moduleOutput).join('\n')}
`
  }

  moduleVersions(module: Module): string {
    if (!module.versions || module.versions.length === 0) {
      return 'None'
    }

    return module.versions.map(v => `- [${v.version}](https://${module.id}/releases/tag/${v.version})`).join('\n')
  }

  license(module: Module): string {
    return module.license || 'Apache License 2.0'
  }
}
