apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: baseline-ocp
spec:
  modules:
    - name: ibm-vpc-gateways
    - name: ibm-ocp-vpc
      variables:
        - name: flavor
          important: true
    - name: openshift-cicd
