apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: multicloud-cluster
spec:
  modules:
    - name: ocp-login
    - name: argocd-bootstrap
    - name: console-link-job
    - name: cluster-config
      alias: config
      variables:
        - name: banner_text
          important: true
