name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ '**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build
        run: |
          npm install
          npm test
          npm run build

      - name: Install pkg
        run: npm install -g pkg

      - name: Build Asset
        run: |
          pkg -o iascable --options no-warnings .
          ls iascable*

          check_file() {
            local name="$1"
            if [[ ! -f "${name}" ]]; then
              echo "File missing: ${name}" >&2
              ls >&2
              exit 1
            fi
          }

          check_file iascable-linux-x64 || exit 1
          check_file iascable-linux-arm64 || exit 1
          check_file iascable-macos-x64 || exit 1
          check_file iascable-macos-arm64 || exit 1
          check_file iascable-alpine-x64 || exit 1
          check_file iascable-alpine-arm64 || exit 1
